version: '3'  

services:
  web:
    build: .
    ports:
      - "8080:8000"
      - "5678:5678"
    depends_on: 
      - postgres_db  

  postgres_db:
    image: postgres:latest 
    container_name: ecommerce_database  
    restart: always
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
    driver: local
